name: Gardinsadvancement
version: '0.5.1'
main: org.gardin.gardinsadvancement.Gardinsadvancement
api-version: '1.21'
load: POSTWORLD
depend: [PlaceholderAPI,UltimateAdvancementAPI]
softdepend: [CraftEngine]
commands:
  gardinsadvancement:
    aliases: [ga]
    description: GardinsAdvancement 主命令
    usage: /<command> reload|grant <player> <namespace:name|all>|revoke <player> <namespace:name|all>|placeholder
permissions:
  gardinsadvancement.reload:
    description: 允许重载 GardinsAdvancement 设置
    default: op
  gardinsadvancement.manage:
    description: 允许手动给予或移除玩家进度
    default: op
  gardinsadvancement.placeholder:
    description: 允许查看 GardinsAdvancement 提供的 PlaceholderAPI 字段
    default: op
